services:
  # -- Example web service
  web:
    image: nginx
    environment:
      # -- Port number for the web server
      PORT: ${PORT:-8080}
      # -- Database connection string
      DATABASE_URL: postgresql://localhost/myapp

  # -- Example API service
  api:
    image: myapi
    environment:
      # -- API key for external service, no default value
      - API_KEY=${API_KEY}
      # -- Debug mode flag. Can be true | false
      - DEBUG=${DEBUG-false}
